<?php

namespace App\Filament\Resources\Products\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ProductInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('name'),
                TextEntry::make('names')
                    ->columnSpanFull(),
                TextEntry::make('slug'),
                TextEntry::make('permalink')
                    ->placeholder('-'),
                TextEntry::make('type')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('status')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('catalog_visibility')
                    ->placeholder('-'),
                TextEntry::make('sku')
                    ->label('SKU')
                    ->placeholder('-'),
                TextEntry::make('regular_price')
                    ->placeholder('-'),
                TextEntry::make('sale_price')
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_from')
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_to')
                    ->placeholder('-'),
                TextEntry::make('external_url')
                    ->placeholder('-'),
                TextEntry::make('low_stock_amount')
                    ->placeholder('-'),
                TextEntry::make('weight')
                    ->placeholder('-'),
                TextEntry::make('shipping_class')
                    ->placeholder('-'),
                TextEntry::make('average_rating')
                    ->placeholder('-'),
                TextEntry::make('stock_status')
                    ->badge()
                    ->placeholder('-'),
                TextEntry::make('price_html')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('short_description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('descriptions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('short_descriptions')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('featured')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('on_sale')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('purchasable')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('virtual')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('downloadable')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('manage_stock')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('sold_individually')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('shipping_required')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('shipping_taxable')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('reviews_allowed')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('has_options')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('total_sales')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('stock_quantity')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('shipping_class_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rating_count')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('menu_order')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('parent_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
