<?php

namespace App\Models;

use App\Http\Integrations\WP\Models\WPCategoryResponse;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'wp_data';

    protected $casts = [
        'data' => 'array'
    ];

    public function newEloquentBuilder($query)
    {
        return parent::newEloquentBuilder($query)
            ->where('type', 'category'); // TODO: Change the autogenerated stub
    }
}
