<?php

namespace App\Models;

use App\Http\Integrations\WP\Models\WPTagResponse;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{

    protected $table = 'wp_data';

    protected $casts = [
        'data' => WPTagResponse::class
    ];

    public function newEloquentBuilder($query)
    {
        return parent::newEloquentBuilder($query)
            ->where('type', 'tag'); // TODO: Change the autogenerated stub
    }
}
